Repository lokalise/fastify-extras, pull requests merged in 2023-09, with the labels that each got.

#74 Update to the next newrelic semver major and some other dependencies
  lib/plugins/metricsPlugin.ts
  lib/plugins/requestContextProviderPlugin.ts
  package.json
Labels: major

#75 Implement Prometheus-based healthcheck
  .eslintrc.json
  lib/index.ts
  lib/plugins/healthcheckMetricsPlugin.spec.ts
  lib/plugins/healthcheckMetricsPlugin.ts
  package.json
Labels: minor

#76 Fix prom healthcheck return type
  lib/plugins/healthcheckMetricsPlugin.spec.ts
  lib/plugins/healthcheckMetricsPlugin.ts
Labels: patch

#77 [AP-372] Modify public healthcheck to use /health endpoint by default and support optional checks
  lib/index.ts
  lib/plugins/publicHealthcheckPlugin.spec.ts
  lib/plugins/publicHealthcheckPlugin.ts
Labels: major

#78 Include healthchecks in response
  lib/plugins/healthcheckMetricsPlugin.spec.ts
  lib/plugins/publicHealthcheckPlugin.spec.ts
  lib/plugins/publicHealthcheckPlugin.ts
Labels: minor

#82 * add FastifyReplyWithPayload type
  lib/index.ts
  lib/types.ts
Labels: patch

#83 Common healthcheck wrapping functions
  lib/index.ts
  lib/plugins/healthcheck/healthcheckCommons.ts
  lib/plugins/healthcheck/healthcheckMetricsPlugin.spec.ts
  lib/plugins/healthcheck/healthcheckMetricsPlugin.ts
  lib/plugins/healthcheck/publicHealthcheckPlugin.spec.ts
  lib/plugins/healthcheck/publicHealthcheckPlugin.ts
  package.json
Labels: minor

#84 Add missing export
  lib/index.ts
Labels: patch
