Repository lokalise/fastify-extras, pull requests merged in 2024-04, with the labels that each got.

#138 Amplitude adapter
  CHANGELOG.md
  README.md
  lib/index.ts
  lib/plugins/amplitude/Amplitude.ts
  lib/plugins/amplitude/AmplitudeAdapter.spec.ts
  lib/plugins/amplitude/AmplitudeAdapter.ts
  lib/plugins/amplitude/amplitudePlugin.spec.ts
  lib/plugins/amplitude/amplitudePlugin.ts
Labels: minor

#139 AP-3190 Reexport of addFeatureFlag.
  lib/index.ts
  lib/plugins/bugsnagPlugin.ts
  package.json
Labels: minor

#142 Updating node-core
  CHANGELOG.md
  package.json
Labels: patch

#144 Switch to CommonLogger interface
  .eslintrc.json
  .github/dependabot.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  lib/plugins/opentelemetry/spanProcessors.ts
  lib/plugins/requestContextProviderPlugin.ts
  package.json
Labels: major
