Repository lokalise/fastify-extras, pull requests merged in 2024-09, with the labels that each got.

#189 AP-5015 update bullmq metrics plugin to use redis configs instead of redis instances
  README.md
  lib/plugins/bull-mq-metrics/MetricsCollector.ts
  lib/plugins/bull-mq-metrics/ObservableQueue.ts
  lib/plugins/bull-mq-metrics/queueDiscoverers.ts
  lib/plugins/bullMqMetricsPlugin.spec.ts
  lib/plugins/bullMqMetricsPlugin.ts
  package.json
  test/mocks/TestDepedendencies.ts
Labels: major

#193 missing export
  lib/index.ts
Labels: patch

#194 Add extra context for error reporter
  lib/errors/errorHandler.spec.ts
  lib/errors/errorHandler.ts
  lib/plugins/amplitude/AmplitudeAdapter.spec.ts
  lib/plugins/amplitude/amplitudePlugin.spec.ts
  lib/plugins/bullMqMetricsPlugin.spec.ts
  test/mocks/TestBackgroundJobProcessor.ts
  test/mocks/TestDependencies.ts
  test/setup.ts
  vitest.config.mts
Labels: minor

#200 Switch to fastify 5
  lib/plugins/amplitude/amplitudePlugin.ts
  lib/plugins/bugsnagPlugin.ts
  lib/plugins/bullMqMetricsPlugin.ts
  lib/plugins/healthcheck/healthcheckMetricsPlugin.ts
  lib/plugins/healthcheck/publicHealthcheckPlugin.ts
  lib/plugins/metricsPlugin.ts
  lib/plugins/newrelicTransactionManagerPlugin.ts
  lib/plugins/requestContextProviderPlugin.ts
  lib/plugins/splitIOFeatureManagerPlugin.ts
  lib/plugins/unhandledExceptionPlugin.ts
  lib/types.ts
  package.json
Labels: major

#201 Update error handler to accomodate for changes in fastify-type-provider-zod
  lib/errors/errorHandler.spec.ts
  lib/errors/errorHandler.ts
  package.json
Labels: minor

#202 Use more fastify5-friendly logger definition
  lib/plugins/bullMqMetricsPlugin.spec.ts
  lib/plugins/healthcheck/healthcheckMetricsPlugin.spec.ts
  lib/plugins/metricsPlugin.spec.ts
  lib/plugins/metricsPlugin.ts
  lib/plugins/prometheus/PrometheusCounterTransactionManager.spec.ts
Labels: minor

#203 Adjust FastifyInstance types
  lib/errors/errorHandler.ts
  lib/index.ts
  lib/plugins/healthcheck/healthcheckCommons.ts
  lib/plugins/healthcheck/healthcheckMetricsPlugin.ts
  lib/plugins/healthcheck/publicHealthcheckPlugin.ts
  lib/plugins/pluginsCommon.ts
Labels: patch

#204 Explicit plugin types
  lib/plugins/amplitude/amplitudePlugin.ts
  lib/plugins/bugsnagPlugin.ts
  lib/plugins/bullMqMetricsPlugin.ts
  lib/plugins/healthcheck/healthcheckMetricsPlugin.ts
  lib/plugins/healthcheck/publicHealthcheckPlugin.ts
  lib/plugins/metricsPlugin.ts
  lib/plugins/newrelicTransactionManagerPlugin.ts
  lib/plugins/requestContextProviderPlugin.ts
  lib/plugins/splitIOFeatureManagerPlugin.ts
  lib/plugins/unhandledExceptionPlugin.ts
Labels: minor
