Repository lokalise/fastify-extras, pull requests merged in 2024-10, with the labels that each got.

#205 Add missing dependency
  package.json
Labels: patch

#208 Update to a newer BullMQ
  package.json
Labels: major

#210 AP-5780 Accept groups in Amplitude track calls
  lib/plugins/amplitude/AmplitudeAdapter.spec.ts
  lib/plugins/amplitude/AmplitudeAdapter.ts
Labels: minor
