Repository lokalise/fastify-extras, pull requests merged in 2024-08, with the labels that each got.

#179 Add support for newrelic 12
  .github/workflows/ci.yml
  package.json
Labels: patch

#180 AP-4667 PreHandler for static tokens.
  README.md
  lib/index.ts
  lib/route-utils/authPreHandlers.spec.ts
  lib/route-utils/authPreHandlers.ts
  package.json
Labels: minor

#181 adjust bull mq metrics
  lib/plugins/bull-mq-metrics/MetricsCollector.ts
  lib/plugins/bull-mq-metrics/ObservableQueue.ts
  lib/plugins/bullMqMetricsPlugin.spec.ts
  package.json
Labels: minor

#183 Update dependencies
  biome.json
  lib/plugins/bull-mq-metrics/queueDiscoverers.ts
  package.json
  tsconfig.json
  tsconfig.lint.json
  vitest.config.mts
Labels: minor

#186 AP-4397 support for multiple redis clients in BullMQ metrics
  README.md
  lib/plugins/bull-mq-metrics/MetricsCollector.ts
  lib/plugins/bull-mq-metrics/queueDiscoverers.ts
  lib/plugins/bullMqMetricsPlugin.spec.ts
  lib/plugins/bullMqMetricsPlugin.ts
  package.json
Labels: major

#188 node-core must be a peer dependency
  package.json
Labels: patch
