Repository lokalise/fastify-extras, pull requests merged in 2024-06, with the labels that each got.

#157 Forcing error-utils 1.2.1
  package.json
Labels: patch

#158 Forcing error-utils 1.2.2
  package.json
Labels: patch

#159 Remove direct dependency on ALS
  README.md
  lib/index.ts
  lib/plugins/opentelemetry/prismaOtelTracingPlugin.ts
  lib/plugins/opentelemetry/spanProcessors.ts
  lib/plugins/requestContextProviderPlugin.ts
  lib/plugins/unhandledExceptionPlugin.ts
  package.json
Labels: major

#160 Use backend-http-client
  lib/plugins/healthcheck/healthcheckMetricsPlugin.spec.ts
  lib/plugins/metricsPlugin.spec.ts
  package.json
Labels: skip-release

#163 Support user_id "SYSTEM"
  lib/plugins/amplitude/AmplitudeAdapter.spec.ts
  lib/plugins/amplitude/AmplitudeAdapter.ts
Labels: minor

#164 Fix error logging
  lib/errors/errorHandler.ts
Labels: patch

#165 Enhanced error reporting to include generic and other error types
  lib/errors/errorHandler.spec.ts
  lib/errors/errorHandler.ts
Labels: patch
