Repository lokalise/fastify-extras, pull requests merged in 2024-07, with the labels that each got.

#174 Add Redis
  .github/workflows/ci.yml
  docker-compose.yml
  package.json
Labels: skip-release

#173 AIM-402 Add BullMQ metrics plugin
  .env.test
  .eslintrc.json
  .github/workflows/ci.yml
  .gitignore
  README.md
  lib/index.ts
  lib/plugins/bull-mq-metrics/CollectionScheduler.ts
  lib/plugins/bull-mq-metrics/MetricsCollector.ts
  lib/plugins/bull-mq-metrics/ObservableQueue.ts
  lib/plugins/bull-mq-metrics/queueDiscoverers.ts
  lib/plugins/bullMqMetricsPlugin.spec.ts
  lib/plugins/bullMqMetricsPlugin.ts
  package.json
  test/mocks/TestBackgroundJobProcessor.ts
  test/mocks/TestDepedendencies.ts
  test/setup.ts
  tsconfig.lint.json
Labels: minor

#175 Fix incorrect TS build
  tsconfig.json
Labels: patch

#177 Move to biome
  .eslintignore
  .eslintrc.json
  .npmignore
  .prettierignore
  .prettierrc.json
  biome.json
  lib/errors/errorHandler.spec.ts
  lib/errors/errorHandler.ts
  lib/index.ts
  lib/jwt-utils/tokenUtils.ts
  lib/plugins/amplitude/AmplitudeAdapter.spec.ts
  lib/plugins/amplitude/amplitudePlugin.spec.ts
  lib/plugins/amplitude/amplitudePlugin.ts
  lib/plugins/bugsnagPlugin.ts
  lib/plugins/bull-mq-metrics/queueDiscoverers.ts
  lib/plugins/bullMqMetricsPlugin.spec.ts
  lib/plugins/healthcheck/healthcheckMetricsPlugin.spec.ts
  lib/plugins/healthcheck/publicHealthcheckPlugin.spec.ts
  lib/plugins/healthcheck/publicHealthcheckPlugin.ts
  lib/plugins/metricsPlugin.spec.ts
  lib/plugins/metricsPlugin.ts
  lib/plugins/newrelicTransactionManagerPlugin.ts
  lib/plugins/requestContextProviderPlugin.ts
  lib/plugins/splitIOFeatureManagerPlugin.ts
  lib/plugins/unhandledExceptionPlugin.spec.ts
  package.json
  test/mocks/TestDepedendencies.ts
  vitest.config.mts
Labels: skip-release
