Repository lokalise/fastify-extras, pull requests merged in 2025-03, with the labels that each got.

#247 Chore/common tsconfig
  biome.json
  lib/errors/errorHandler.spec.ts
  lib/errors/errorHandler.ts
  lib/index.ts
  lib/jwt-utils/tokenUtils.spec.ts
  lib/jwt-utils/tokenUtils.ts
  lib/plugins/amplitude/AmplitudeAdapter.spec.ts
  lib/plugins/amplitude/AmplitudeAdapter.ts
  lib/plugins/amplitude/amplitudePlugin.spec.ts
  lib/plugins/amplitude/amplitudePlugin.ts
  lib/plugins/bugsnagPlugin.ts
  lib/plugins/bull-mq-metrics/MetricsCollector.ts
  lib/plugins/bull-mq-metrics/ObservableQueue.ts
  lib/plugins/bull-mq-metrics/queueDiscoverers.ts
  lib/plugins/bullMqMetricsPlugin.spec.ts
  lib/plugins/bullMqMetricsPlugin.ts
  lib/plugins/healthcheck/commonHealthcheckPlugin.spec.ts
  lib/plugins/healthcheck/commonHealthcheckPlugin.ts
  lib/plugins/healthcheck/healthcheckCommons.ts
  lib/plugins/healthcheck/healthcheckMetricsPlugin.spec.ts
  lib/plugins/healthcheck/healthcheckMetricsPlugin.ts
  lib/plugins/healthcheck/publicHealthcheckPlugin.spec.ts
  lib/plugins/healthcheck/publicHealthcheckPlugin.ts
  lib/plugins/metricsPlugin.spec.ts
  lib/plugins/metricsPlugin.ts
  lib/plugins/pluginsCommon.ts
  lib/plugins/prometheus/PrometheusCounterTransactionManager.spec.ts
  lib/plugins/requestContextProviderPlugin.spec.ts
  lib/plugins/requestContextProviderPluginTypes.spec.ts
  lib/plugins/splitIOFeatureManagerPlugin.spec.ts
  lib/plugins/splitIOFeatureManagerPlugin.ts
  lib/plugins/stripTrailingSlashPlugin.spec.ts
  lib/plugins/unhandledExceptionPlugin.spec.ts
  lib/route-utils/authPreHandlers.spec.ts
  lib/types.ts
  package.json
  test/mocks/TestBackgroundJobProcessor.ts
  test/mocks/TestDependencies.ts
  tsconfig.build.json
  tsconfig.json
  tsconfig.lint.json
Labels: major

#248 Fixing new relic require
  lib/plugins/newrelicTransactionManagerPlugin.ts
Labels: patch

#249 Moving new relic to local instance
  lib/plugins/newrelicTransactionManagerPlugin.ts
Labels: patch

#251 Using newrelic default
  lib/plugins/newrelicTransactionManagerPlugin.ts
Labels: patch

#250 Failing in case newrelic is not defined
  lib/plugins/newrelicTransactionManagerPlugin.ts
Labels: minor

#255 feat: Expose NR user & controller methods
  lib/plugins/newrelicTransactionManagerPlugin.ts
Labels: minor

#257 Support synchronous creation of noop newrelic manager
  lib/plugins/newrelicTransactionManagerPlugin.ts
  package.json
Labels: minor
